import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import HomePage from "./home/index";
import NavbarPC from "./components/navbarpc";
import NavbarMB from "./components/navbarmb";
import Footer from "./components/footer";

const Home: NextPage = (props) => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/criti_logo.png" />
      </Head>
      <div>
        <div className="nav-pc">
          <NavbarPC />
        </div>
        <div className="nav-mobile">
          <NavbarMB />
        </div>
        <HomePage />

        <Footer />
      </div>
    </div>
  );
};

export default Home;
